In [4]:
import random
for i in range(3):
    print(random.random())
x = 10

0.5100034077838423
0.3124773078129498
0.00030341049661952724

In [42]:
import numpy as np
import pandas as pd
import matplotlib as mlp
import seaborn as sns

In [43]:
df = pd.read_csv('C:/Users/osumb/notebooks/assignment/flights.csv')

In [44]:
df.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0

In [45]:
df['air_time'].dtype

dtype('float64')

In [46]:
df['day'].dtype

dtype('int64')

In [47]:
df['year'].dtype

dtype('int64')

In [48]:
df['origin'].dtype

dtype('O')

In [49]:
df = df.groupby(['air_time'])

In [51]:
df.mean(['air_time'])

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,flight,distance,hour,minute
air_time,,,,,,,,,,,
21.0,2013.0,3.000000,2.000000,1450.000000,-10.000000,1547.000000,-21.000000,2132.000000,184.000000,14.000000,50.000000
23.0,2013.0,6.500000,19.000000,2099.500000,5.000000,2227.500000,11.000000,1332.000000,150.000000,20.500000,49.500000
25.0,2013.0,4.666667,20.666667,1111.000000,-5.333333,1197.666667,-14.000000,1396.000000,101.333333,10.666667,44.333333
26.0,2013.0,7.615385,11.307692,1429.769231,4.384615,1332.461538,0.307692,1425.153846,115.615385,14.076923,22.076923
27.0,2013.0,7.200000,12.800000,599.200000,-2.800000,679.400000,-14.300000,1704.000000,95.400000,5.600000,39.200000
...,...,...,...,...,...,...,...,...,...,...,...
666.0,2013.0,4.000000,10.000000,1431.000000,61.000000,2008.000000,113.000000,15.000000,4963.000000,14.000000,31.000000
667.0,2013.0,1.000000,9.000000,1340.000000,-1.000000,2019.000000,44.000000,15.000000,4963.000000,13.000000,40.000000
671.0,2013.0,3.000000,15.000000,1342.000000,7.000000,1924.000000,48.000000,15.000000,4963.000000,13.000000,42.000000
676.0,2013.0,11.000000,12.000000,936.000000,6.000000,1630.000000,60.000000,15.000000,4963.000000,9.000000,36.000000
695.0,2013.0,3.000000,17.000000,1337.000000,2.000000,1937.000000,61.000000,15.000000,4963.000000,13.000000,37.000000